apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: latzo.azurecr.io/quickstart-k8s-backend:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_MESSAGE
        - name: NAMESPACE_FILTER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NAMESPACE_FILTER
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
