apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: latzo.azurecr.io/quickstart-k8s-backend:1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_MESSAGE
        - name: REDIS_HOST
          value: "redis-service.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
